### ISSUE TITLE
pyusb issues

### ISSUE THREAD

**Issue by Shmadul** [axi0mX/ipwndfu#10]
When i try and Run ipwndfu this is the result i get
 (Yes i have installed pyusb and libusb already I am on Yosemite 10.10)

./ipwndfu 
Traceback (most recent call last):
  File "~/ipwndfu/ipwndfu", line 6, in <module>
    import usb # pyusb: use 'pip install pyusb' to install this module
ImportError: No module named usb

**Comment by axi0mX** [comment]
You must have 2 pythons on your Mac. Usually you don't want that. The following should fix it, by removing it from brew:

brew rm python
pip install pyusb

If pip is missing, follow README to install it from the official site.

**Comment by Shmadul** [comment]
ipwndfu -U <hex data>	# encrypt hex data with UID key (YAY it works )
