### ISSUE TITLE
iPhone X Verbose boot demo doesn't work as intended 

### ISSUE THREAD

**Issue by meowox** [axi0mX/ipwndfu#106]
`╭─meow at menhera in /home/meow/ipwndfu (master ✔)
╰─λ sudo python2.7 ipwndfu --boot                                                 
Heap repaired.
Booted.`
Nothing actually happens. It stays in black screen although device disappears in lsusb.
Pressed power button, logo shows up and it blinked once and booted normally but took longer time.

**Comment by debouncedgit** [comment]
Are you on iOS 13.1.1 or 13.1.2, afaik it isn't available below.

**Comment by meowox** [comment]
Sorry for not checking twitter. Some README changes would be nice.

**Comment by iM4CH3T3** [comment]
Getting this on iPhone 8 iOS 13.1.1 
![Image](https://i.imgur.com/pSF7PEg.jpg)

**Comment by iM4CH3T3** [comment]
And this on 13.1.2
![Image](https://i.imgur.com/HAwYNys.jpg)

**Comment by iM4CH3T3** [comment]
Same again it actually simply reboots/panics
![Image](https://i.imgur.com/bM2EGoF.jpg)

**Comment by iM4CH3T3** [comment]
Forgot to mention that I’m running Ubuntu and it actually works but without the verbose boot somehow 🤷‍♂️
iPhone 8 iOS 13.1.2
![Image](https://i.imgur.com/CMHErFb.jpg)
