### ISSUE TITLE
İphone 4s icloud unulock

### ISSUE THREAD

**Issue by amilim** [axi0mX/ipwndfu#114]

**Comment by fgarcia14** [comment]
You're idiot

**Comment by amilim** [comment]
fgarcia14 Is it stupid to ask for help?  The thing is, stupidity doesn't help!

**Comment by timonline** [comment]
It’s 

> fgarcia14 Is it stupid to ask for help? The thing is, stupidity doesn't help!

It’s stupid to post an ISSUE when you’re looking for help.

Reddit, Twitter, blogs, etc... would serve you better

If it wasn’t clear, an “issue” means the existing has a bug or problem working versus you being a failure at USING the product.

Learning the difference between a question and an issue would serve you well

**Comment by xFahrenheightx** [comment]
> fgarcia14 Is it stupid to ask for help? The thing is, stupidity doesn't help!

If you actually read the readme you'd see this project isn't for bypassing iCloud. As well why the hell did you use an account just to ask a stupid question that's borderline illegal? That's your only contribution on Github. Get out and stop stealing devices. Contact Apple support or the previous device owner.

**Comment by fgarcia14** [comment]
Thanks @xFahrenheightx
