### ISSUE TITLE
iPad Pro 9,7 // ERROR: This device is not supported.

### ISSUE THREAD

**Issue by technisat** [axi0mX/ipwndfu#121]
user ~ % /Users/user/Downloads/ipwndfu-master\ 2/ipwndfu -p
Found: CPID:8001 CPRV:10 CPFM:03 SCEP:01 BDID:0A ECID:001A68401807C226 IBFL:1C SRTG:[iBoot-2481.0.0.2.1]
ERROR: This device is not supported.

Any clue?

**Comment by EWouters** [comment]
Please check #67 and close this issue.
