### ISSUE TITLE
TypeError: can't contac str to bytes

### ISSUE THREAD

**Issue by debouncedgit** [axi0mX/ipwndfu#124]
Using Linux Manjaro and an up-to-date Geohots fork (mind you, no one really does support over there). Facing error `TypeError: can't contac str to bytes` was given a full traceback and can't figure  out the fix. Below is an image on imgur of my terminal, thanks!

https://i.imgur.com/JlK4b2b.png

**Comment by EWouters** [comment]
That is a syntax error in geohots code. You should not open an issue here for that. Please close this issue.

(The error is related to Python 3's syntax changes with respect to [strings](https://python-future.org/compatible_idioms.html#byte-string-literals). To fix this put a `b` in front of the string like `b'\0'` to make Python 3 recognize it as a byte-string. However, the repo you are using is likely to contain more errors even when you fix this. It is not meant to work out of the box.)
