### ISSUE TITLE
Help with: "bash: ./ipwndfu: Is a directory"

### ISSUE THREAD

**Issue by Warmine05** [axi0mX/ipwndfu#130]
No matter what ./ipwndfu command I use I always get "bash: ./ipwndfu: Is a directory". I know way to little about linux-commands/(programing) to have a clue what to do

What I can say is that I have installed libusb, my iPhone is in DFU mode and I am using Linux (Zorin). 

Help would be appreciated!

**Comment by EWouters** [comment]
Please refer to #107 and check [this](https://opensource.guide/how-to-contribute/#communicating-effectively) guide on how to contribute to open source.

Basically, if you are unable to follow along with the README you will not learn much from this repo. You can learn much more from taking some online courses on edX or Coursera, etc. about this topic.

(Try `cd ipwndfu` then `./ipwndfu -p --boot`)

Please close this issue.

**Comment by Warmine05** [comment]
Thanks that worked.
