### ISSUE TITLE
My iphone 6s wont work with this?

### ISSUE THREAD

**Issue by agentk2** [axi0mX/ipwndfu#138]
Found: CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:0000073628BC69C8 IBFL:1C SRTG:[iBoot-2234.0.0.3.3]
ERROR: This device is not supported.
Ios 12.4, has been jailbroken.

**Comment by Saraseti** [comment]
same here get the same error message and my device is jailbroken.

**Comment by alyxandraio** [comment]
checkm8 supports devices from A5-A11, however support for some devices (like the iPhone 6s) has not been added yet. If you have an iPhone 6s, you either have an S8000 or S8003 processor and in the readme it states that these processors are awaiting support.

Edit: I looked closer at your error message and from the bootrom version number, it appears you have an N71AP model iPhone 6s, which runs the S8000 processor.

**Comment by EWouters** [comment]
Please check #67 and close this issue.
