### ISSUE TITLE
ERROR: This device is not supported

### ISSUE THREAD

**Issue by finlandhl** [axi0mX/ipwndfu#149]
I get this 'ERROR...' every time I try to run the command on Mac.
iDevice is iPhone 4s (simlocked)

Need help please!

**Terminal:**

_`Last login: Wed Oct  9 19:57:22 on ttys000
finlandlasme@mewltm ipwndfu-master % sudo python ./ipwndfu -p
Password:
Found: CPID:8940 CPRV:21 CPFM:03 SCEP:01 BDID:08 ECID:000001A60E143D8A IBFL:00 SRTG:[iBoot-838.3]
ERROR: This device is not supported.
finlandlasme@mewltm ipwndfu-master % '_

**Comment by EWouters** [comment]
Please check #67 and close this issue.
