### ISSUE TITLE
Add more compatible devices

### ISSUE THREAD

**Issue by gebeto** [axi0mX/ipwndfu#154]
What I need to read to add more compatible devices?

I have the device with CPID:8001 (iPad Pro 9.7 2016, A9X)
How and where I can found that magical values?
```
gUSBDescriptors
gUSBSerialNumber
usb_create_string_descriptor
gUSBSRNMStringDescriptor
PAYLOAD_DEST
```

**Comment by N00byEdge** [comment]
Either the ROM or the .h sources for your device.

**Comment by 0x41c** [comment]
Explain?

**Comment by PenisPaperCut** [comment]
Me too, I want to know the answer for this. This would be great to know because I have an SE.
