### ISSUE TITLE
iPad Air 2 : A1566

### ISSUE THREAD

**Issue by tmslacker** [axi0mX/ipwndfu#165]
This device is not supported.  A8X?  I have a 64GB model.

**Comment by ps4gentoo** [comment]
Bitte lesen Sie: # 107

**Comment by Valentinez** [comment]
This is an Issue how?

Please Read: [#107](https://github.com/axi0mX/ipwndfu/issues/107)

Took me 4 days to get my iPad Mini 3 to work,
Using Ubuntu 18.04, and Tinkering with the Code.

_Which, I DO NOT recommend unless you know what you're doing._

**Comment by tmslacker** [comment]
My apologies to everyone’s hard work & time.  My noob was showing.  #107.
