### ISSUE TITLE
Not an issue But a question

### ISSUE THREAD

**Issue by Err0ring** [axi0mX/ipwndfu#169]
CAN I USE THIS FOR IPHONE X ?
and is CYDIA included ?

and sorry to bother you with this questions BUT this is the place where I can ask :( !

thanks.

**Comment by timonline** [comment]
You’re better off going anywhere else on the internet if you’re asking these questions

**Comment by Einstein2150** [comment]
The stupidness of mankind is infinite big 🤦🏻‍♂️
