### ISSUE TITLE
Please support iPad mini 4

### ISSUE THREAD

**Issue by wqhqq1** [axi0mX/ipwndfu#174]
It says the device not supported.

**Comment by Valentinez** [comment]
Reading the README file is an important first step before downloading anything~!

If not, here is important bits:
```
Current SoC support: s5l8947x, s5l8950x, s5l8955x, s5l8960x, t8002, t8004, t8010, t8011, t8015
                                                                  vvvYour SoC
Future SoC support: s5l8940x, s5l8942x, s5l8945x, s5l8747x, t7000, t7001, s7002, s8000, s8001, s8003, t8012
```
Your iPad Mini 4 has an Apple A8 SoC, which translates to: [CPID: T7000].

Listed under **_FUTURE_ Support**.
Means they are working on it.
_**Please be Patient~!**_

You should also read: [#107 ](https://github.com/axi0mX/ipwndfu/issues/107)
