### ISSUE TITLE
iPhone 6s on iOS 13.1.2 doesn't verbose boot

### ISSUE THREAD

**Issue by slickpads** [axi0mX/ipwndfu#180]
I saw a youtube that in his about it said he was running on 13.1.2 and used the checkm8 and PwnedDFU mode to verbose boot. I can't do the same thing as it gives me the "this device is not supported" error.

**Comment by luapp** [comment]
Verbose boot only works on iPhone X

**Comment by EWouters** [comment]
Please check #67 and close this issue.
