### ISSUE TITLE
ImportError: No module named usb

### ISSUE THREAD

**Issue by albyvar** [axi0mX/ipwndfu#2]
iMac-di-alby:ipwndfu alby$ ./ipwndfu -x
Traceback (most recent call last):
  File "./ipwndfu", line 5, in <module>
    import binascii, datetime, getopt, hashlib, struct, subprocess, sys, time, usb
ImportError: No module named usb

Already installed python and pyusb

**Comment by fothot** [comment]
if you are running mac os make sure to install libusb and the patch for the sierra/el capitan. If you are on a linux machine run "pip install -U pip" in order to update your pip and then "pip install pyusb" to make sure you are running the latest pyusb.

**Comment by albyvar** [comment]
Thank you, but i finally solved by just moving the pyusb folder to the iPwn folder!
