### ISSUE TITLE
Bypass Activation (no SIM) on 2011 Week 36 iPhone 3GS iOS 5.1.1 

### ISSUE THREAD

**Issue by OothecaPickle** [axi0mX/ipwndfu#27]
I have a 2011 Week 36 iPhone 3GS (new BootROM) that I purchased off eBay, successfully restored to iOS 5.1.1 using a 24kpwn IPSW made with redsn0w, and booted using alloc8. My issue, however, is that the device did not come with a SIM card, so I am unable to get past activation. Is there any way for me to bypass activation on this device without a SIM? (I don't care about cellular capabilities.) Thanks in advance, Zach. :) :)

**Comment by axi0mX** [comment]
Try this:
https://www.youtube.com/watch?v=cxKDo9aF4pQ

**Comment by OothecaPickle** [comment]
thanks a bunch; worked perfectly! :)
