### ISSUE TITLE
When iOS15.2 will be able to jailbreak in A11?

### ISSUE THREAD

**Issue by Misakei** [axi0mX/ipwndfu#290]

**Comment by alyxandraio** [comment]
This is not related to this project at all. @Misakei

**Comment by Misakei** [comment]
> This is not related to this project at all. @Misakei
I sent the same message wherever it might be relevant.

**Comment by vadimszzz** [comment]
A11 is pwned. You should tether-downgrade to iOS 14.8 to be able to jailbreak with checkra1n.

checkra1n is now in active development, all questions about iOS support are here: https://github.com/checkra1n/BugTracker/issues
You can ask Siguza about terms of iOS 15.0/15.1/15.2 support
