### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Merculous** [axi0mX/ipwndfu#30]
Traceback (most recent call last):
  File "./ipwndfu", line 77, in <module>
    nor = nor.NorData(dump)
  File "/Users/merculous/Documents/ipwndfu/nor.py", line 11, in __init__
    assert img2_crc == binascii.crc32(dump[:48]) & 0xffffffff
AssertionError

**Comment by axi0mX** [comment]
That probably happened because a restore failed. It says that NOR does not have valid data flashed to it. You must successfully restore a 24Kpwn IPSW before using ```-x``` option.

**Comment by Merculous** [comment]
Ok. I thought it was a 24kpwn ipsw... I guess not.

**Comment by axi0mX** [comment]
This error can happen regardless of the IPSW you use. What matters is whether the restore process succeeded and whether NOR was flashed correctly.

**Comment by Merculous** [comment]
That's what I thought. I'm currently working on iOS 3.0 and iOS 3.0.1 bundles for the 3GS and wanted to try it using the patches I created. I'll have to add a few things for the created ipsw

**Comment by Merculous** [comment]
Also trying to fix the iOS 3.1.3 problem when restoring with sn0wbreeze ipsw. That's the main issue towards the issue.

**Comment by iPhoneGuy1101** [comment]
Merculos If you can not restore to a sn0wbreeze ipsw, try a virtual machine running macOS and run pwnagetool, it worked for me. (https://techsviewer.com/how-to-install-mac-os-x-el-capitan-on-pc-on-virtualbox/ )
