### ISSUE TITLE
Does not work on 8GB 3GS.

### ISSUE THREAD

**Issue by neheb** [axi0mX/ipwndfu#34]
Figured I should post this. The 8GB model I believe came with iOS 6 out of the box. Restoring to 4.3.3 errors out. Restoring to 5.x just freezes iTunes in the preparing stage. Does not get out of recovery mode.

redsn0w does not support Custom IPSW with iOS 6 so that's pretty much no go.

**Comment by axi0mX** [comment]
Without details it is impossible to say what's not working for you.

However, I have an 8GB iPhone 3GS (new bootrom) from 2010 and I was able to downgrade to iOS 3.1.

**Comment by neheb** [comment]
some info:

FirmwareVersion: iBoot-1537.9.55
HardwareModel: N88AP
HardwarePlatform: s5l8920x
ModelNumber: MC640

i'm going to try restoring using idevicerestore next.

**Comment by neheb** [comment]
nah idevicerestore fails too

NOTE: using cached version data
Found device in Normal mode
Identified device as n88ap, iPhone2,1
Extracting BuildManifest from IPSW
ERROR: Unable to extract BuildManifest from xxx

**Comment by axi0mX** [comment]
What are the first 5 digits in this device's serial number?

**Comment by axi0mX** [comment]
iOS 4.1 is still signed by Apple for iPhone 3GS. What error number do you get when you try to restore the iOS 4.1 IPSW in iTunes?

**Comment by neheb** [comment]
error 20

**Comment by axi0mX** [comment]
Your phone must have been in Recovery Mode. You must do this from DFU Mode. Enter Hardware DFU and try again.

**Comment by neheb** [comment]
so after setting DFU mode, it is restoring now. Didn't know DFU mode was needed.

restore of 4.1 failed with error 10xx (forgot).

restore of 4.3.3 (oldrom) failed with error 3194.

restore of 5.1.1 (oldrom) failed with error 1600.

**Comment by neheb** [comment]
alright retried 5.1.1 with idevicerestore. This time

Success!

iPhone is on 5.1.1.

**Comment by axi0mX** [comment]
Nice. Is this an untethered downgrade using alloc8?

**Comment by neheb** [comment]
I followed the guide with ipwndfu -x. So yes.
