### ISSUE TITLE
Getting this error when use ./ipwndfu -p and ./ipwndfu -x

### ISSUE THREAD

**Issue by CodeyMoore** [axi0mX/ipwndfu#5]
I get this error when typing the command ./ipwndfu -x and ./ipwndfu -p
How do i fix this?

My iPhone 3GS is a New BR on iOS 3.1 after downgrading with 24Kpwn, my mac is running MacOS Sierra 10.12.4

./ipwndfu -p
![screen shot 2017-04-12 at 5 35 17 pm](https://cloud.githubusercontent.com/assets/21144094/24948628/0607c5e8-1faa-11e7-9241-932e25f8af4e.png)

./ipwndfu -x
![screen shot 2017-04-12 at 6 04 24 pm](https://cloud.githubusercontent.com/assets/21144094/24948789/a43aa42e-1faa-11e7-8c92-805361a4f09a.png)

**Comment by axi0mX** [comment]
Read README and make sure all dependencies are installed. This happens when you don't have libusb. You'll need to install it, as well as everything else mentioned in README.

https://github.com/axi0mX/ipwndfu/blob/master/README.md

**Comment by CodeyMoore** [comment]
I have libusb installed though?

**Comment by axi0mX** [comment]
Why do you believe it is installed?

**Comment by CodeyMoore** [comment]
it says that its installed but not linked

**Comment by CodeyMoore** [comment]
![screen shot 2017-04-12 at 6 26 00 pm](https://cloud.githubusercontent.com/assets/21144094/24949681/a41ef672-1fad-11e7-94c7-5d22ece9cac6.png)

**Comment by axi0mX** [comment]
OK, that's good then. Can you "brew link libusb", and try again?

**Comment by axi0mX** [comment]
OK. "brew link --overwrite libusb"

Afterwards, you'll need to check the SHA1 hash of the file again, and if it is the non-patched one you might need to patch it again.

**Comment by CodeyMoore** [comment]
Its working now, i just had to overwrite it. thanks for ur help :)

**Comment by CodeyMoore** [comment]
i have another issue its saying that my SHA1 hash is completely different to the normal macOS sierra hash

**Comment by axi0mX** [comment]
This is an experiment, but it should work.

I added the patched libusb dylib (matching the posted SHA1 hash of patched libusb) here. Try replacing your dylib with this one. If it works, this might be a better solution than developing patches for all possible versions.

https://github.com/axi0mX/ipwndfu/blob/master/libusb-dylib/libusb-1.0.0.dylib

**Comment by CodeyMoore** [comment]
I got everything to work i just reinstalled libusb. but im getting an error saying that n88ap-iBSS-4.3.5.img3 is corrupted or wrong. but im not using ios 4.3.5 im using ios 3.1

**Comment by axi0mX** [comment]
You must get that file from 4.3.5. Other versions won't work for now.

**Comment by CodeyMoore** [comment]
Oh ok, but i downgraded my iphone to 4.1 and also downgraded the baseband to the ipad one, will that mess with anything?

**Comment by axi0mX** [comment]
Downgrading iOS to stock 4.1 IPSW before restoring to custom 24Kpwn IPSW won't break anything. I don't know about iPad baseband, that might.

**Comment by CodeyMoore** [comment]
no to worry ill just hacktivate it

**Comment by CodeyMoore** [comment]
i downloaded ios 4.3.5 and extracted the iBBS but its still saying that its corrupted or wrong

**Comment by axi0mX** [comment]
Did you get 4.3.5 for iPhone2,1? Did you make sure you replaced the file? Verify the SHA1 hashes match these.

$ openssl sha1 iPhone2,1_4.3.5_8L1_Restore.ipsw 
SHA1(iPhone2,1_4.3.5_8L1_Restore.ipsw)= 80119c009590066dc093ccaeafc9056c05fb73ff

$ openssl sha1 n88ap-iBSS-4.3.5.img3 
SHA1(n88ap-iBSS-4.3.5.img3)= eb90af5310a958e6186f32c1440002962d1f975d

**Comment by CodeyMoore** [comment]
The ipsw didnt download properly, it half downloaded and said it was done. My internet is bad...

**Comment by axi0mX** [comment]
Fixed per https://twitter.com/BLINGSTA69/status/852107768836243456
