### ISSUE TITLE
A8X and A10X not supported?

### ISSUE THREAD

**Issue by 0ch4rl1e0** [axi0mX/ipwndfu#58]

**Comment by alessaba** [comment]
A5-A11 are compatible
A10X support is already there for sure
close the issue please. you can find this sort of info everywhere

**Comment by 0ch4rl1e0** [comment]
stfu if you have no idea. with A8X it says device not compatible on ipwndfu and i think A10X as well too.

**Comment by 0ch4rl1e0** [comment]
he has to add A8X

**Comment by alessaba** [comment]
i have a A10X ¯\_(ツ)_/¯

**Comment by natherine** [comment]
How is this an issue? He literally said t7001 will be supported in the future.

**Comment by 2Eggsss** [comment]
As mentioned previously, there is no current support for T7001 and it will be added in the future. Please close this issue.

**Comment by 0ch4rl1e0** [comment]
okay
