### ISSUE TITLE
IPHONE 6 This device is not supported Error

### ISSUE THREAD

**Issue by erdemkap** [axi0mX/ipwndfu#70]
Erdem-MacBook-Air:ipwndfu-master erdem$ ./ipwndfu -p
Found: CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:xxxxxxxxxxxxxxxxxx IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
ERROR: This device is not supported.

Do you have any idea about this error?

**Comment by jaresh407** [comment]
./ipwndfu -p
Found: CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:XXXXXXXXXXXXXXX  IBFL:1C SRTG:[iBoot-2234.0.0.3.3]
ERROR: This device is not supported.


Similar problem With Iphone 6S

**Comment by wholivesinapineappleunderthesea** [comment]
If you paid attention to the readme you'd know your device isn't supported...

**Comment by iSn0we** [comment]
The iPhone 6 runs on T7000 (A8), which isnt supported _yet_. 
Same goes for the iPhone 6s which runs on the S8000 (A9) which is also not supported _yet_.

**Comment by jaresh407** [comment]
> The iPhone 6 runs on T7000 (A8), which isnt supported _yet_.
> Same goes for the iPhone 6s which runs on the S8000 (A9) which is also not supported _yet_.

Thanks for the reply iSn0we. Sorry for not reading the README carefully enough spongebob. I'm sure it never happens to you but us Patricks out here do make a mistake every now and then.
