### ISSUE TITLE
iPhone 7 restarts when try to ./ipwndfu -p

### ISSUE THREAD

**Issue by hugyasa** [axi0mX/ipwndfu#73]
I don't know why..

**Comment by yky4589** [comment]
i solved. install libusb-1.0.0-dev and python-libusb1

**Comment by hugyasa** [comment]
<img width="682" alt="Schermata 2019-09-29 alle 10 32 35" src="https://user-images.githubusercontent.com/43371281/65829310-7e1f3880-e2a4-11e9-898a-b51657132712.png">

Thanks 😍
