### ISSUE TITLE
can AppleTV work or need special instructions?

### ISSUE THREAD

**Issue by Rovel** [axi0mX/ipwndfu#82]
since most of appleTv have those same processors can this work on them right away or needs additional work in the scripts??

**Comment by EWouters** [comment]
If you can't tell, this is not for you. Wait for someone to release a user-friendly jailbreak.

That being said, [this](https://github.com/axi0mX/ipwndfu/issues/80#issuecomment-536287246) comment contains a list of devices, their CPUs and the state of support for this _developers_ tool.

**Comment by Rovel** [comment]
well a quick research to the processors says that Apple Tv 3.2rd gen (S5L8930) and Apple TV 4K (T8011) so people can query this later on without looking up device processors, and thanks for your great advice @EWouters
