### ISSUE TITLE
syntax error  in python file

### ISSUE THREAD

**Issue by Batuhan4** [axi0mX/ipwndfu#87]
alloc8.py line 71
it must be like that i think 
 print ('ERROR: SecureROM version %s is not supported by alloc8.' %version)

**Comment by 0x06060606** [comment]
use python2 buddy

**Comment by EWouters** [comment]
That is definitely not a syntax error in Python 2. The Python code in this repository is written for Python 2. You have tried to run it on a Python 3 interpreter.

@geohot has ported (parts of) this repo to Python 3 at his fork [here](https://github.com/geohot/ipwndfu).

**Comment by debouncedgit** [comment]
You also could have made a PR, and you would've either gotten accepted or denied. Close this issue. Unnecessary.
