### ISSUE TITLE
This device is not supported.

### ISSUE THREAD

**Issue by KaoTD** [axi0mX/ipwndfu#92]
root@wEiRd-PC:/home/kaotd/ipwndfu# ./ipwndfu -p
Found: CPID:8940 CPRV:21 CPFM:03 SCEP:01 BDID:08 ECID:000001364014FD4C IBFL:00 SRTG:[iBoot-838.3]
ERROR: This device is not supported.
root@wEiRd-PC:/home/kaotd/ipwndfu# 

iPhone 4S iOS 9.3.6

**Comment by Merculous** [comment]
That's because its not supported right now.

**Comment by f0xforce** [comment]
Maybe it never support with CheckM8 currently we waiting for Qwertyuiopz fork...

**Comment by EWouters** [comment]
Please check #67 and close this issue.

**Comment by ghost9866** [comment]
root@ubuntu:/ipwndfu# python ./ipwndfu -p
Found: CPID:8940 CPRV:21 CPFM:03 SCEP:01 BDID:08 ECID:00000235101843CD IBFL:00 SRTG:[iBoot-838.3]
ERROR: This device is not supported.

Please Advise.
